# This is a basic workflow to help you get started with Actions

name: RSpec

# Controls when the workflow will run
on: [push, pull_request]
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #  branches: [ master ]
  # pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # build:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'test'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3
          bundler-cache: true

      - name: Install Dependencies
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup Database
        run: |
         cp config/database.yml.sample config/database.yml
         yarn install --check-files
         bundle exec rake db:create
         bundle exec rake db:schema:load

      - name: Run Rubocop
        run: bundle exec rubocop

      - name: Run Tests
        run: bundle exec rspec
        env:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'test'
          RAILS_TEST_KEY: ${{ secrets.RAILS_TEST_KEY }}
